
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 15s
  group_interval: 2m
  repeat_interval: 1h
  receiver: 'telegram-notifications'

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
      - bot_token: '${BOT_TOKEN}'
        chat_id: ${CHAT_ID}
        parse_mode: 'HTML'
        
        message: |
          {{- range .Alerts }}

          {{- if .Status | eq "firing" -}}
          🔥 <b>FIRING</b> 🔥
          {{- else -}}
          ✅ <b>RESOLVED</b> ✅
          {{- end }}

          <b>Alert:</b> {{ .Annotations.summary }}
          <b>Description:</b> {{ .Annotations.description }}

          <b>Details:</b>
          {{ range .Labels.SortedPairs }} • {{ .Name }}: <code>{{ .Value }}</code>
          {{ end }}
          
          {{- end }}