version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - jaeger
    restart: on-failure

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    restart: unless-stopped
    depends_on:
      - db
      - jaeger
  
  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    depends_on:
      - app
      - postgres-exporter

  grafana:
    image: grafana/grafana-oss:10.2.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    
  locust:
    build:
      context: ./locust 
    ports:
      - "8089:8089" 
    restart: on-failure
    depends_on:
      - app 
    environment:
      LOCUST_HOST: http://app:8080
    
  alertmanager:
    image: prom/alertmanager:v0.27.0
    user: "${UID}:${GID}"
    ports:
      - "9093:9093"
    env_file: .env
    volumes:
      - ./alertmanager:/config
      - alertmanager_data:/data
    command:
      - '--config.file=/config/config.yml'
      - '--storage.path=/data'
    restart: unless-stopped
    depends_on:
      - prometheus
    
  jaeger:
    image: jaegertracing/all-in-one:latest 
    ports:
      - "16686:16686" 
      - "4317:4317"   
    restart: unless-stopped

volumes:
  prometheus_data:
  postgres_data:
  grafana_data:
  alertmanager_data: