{
 "title": "Service Health",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Health Check",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"app:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pastebin_http_requests_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB RPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pastebin_db_queries_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(pastebin_http_requests_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(pastebin_http_request_duration_seconds_bucket{path!=\"/metrics\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(pastebin_http_requests_total{status_code=\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}